### ISSUE TITLE
Crash corrupt jpg

### ISSUE THREAD

**Issue by Pirant0409** [nevaran/Fast-Image-Viewer-Standalone#3]
After fuzzing FIV again, there are still some crashes when opening some corrupt jpg (you can try it yourself with image 1 and 2 below :) )

Visual Studio says it's coming from an unhandled exception in MainWindow line 912

Also, when opening an "healthy" jpg, and then switching to a corrupt jpg from the thumnail list in FIV, the app is also crashing (for the same reason than above, but line 955)

![whitescreen](https://user-images.githubusercontent.com/33604772/129270922-8f22637a-9705-47c1-9ebc-9fa52eee8e95.jpg)

![image 2](https://user-images.githubusercontent.com/33604772/129270924-5dc71ac6-d762-42bd-a1f2-2246935b7e9b.jpg)

Lastly, trying to open the last corrupt image (third image below) directly from the directory by rightclicking it and choosing "open with FIV" makes also the app crash, with visual studio pointing Tools.cs line 110 to 118 to be faulty.

![image 3](https://user-images.githubusercontent.com/33604772/129274173-cefe0dac-e3a1-4a76-b9e2-a2a92d7fb432.jpg)

I should not bother you anymore since my fuzzer wasn't able to make your app crash again with corrupt jpg after fixing those errors :)

**Comment by nevaran** [comment]
Weird, on my end the first image (image 2 and 3 cannot be downloaded) loads just fine with the 8.2.1 build in all 3 possible ways to load the file.
It should just show an error notification on the bottom right
![image](https://user-images.githubusercontent.com/911128/129275882-a066ff13-f1a4-4535-92f6-4a3dedd9ebc2.png)

**Comment by Pirant0409** [comment]
Indeed, i was running it through Visual studio, but when
Image 2 and 3 can be downloaded by right clicking anyware except on the screen but on the square

**Comment by Pirant0409** [comment]
Indeed, wrong call for the first image, it works just fine, my bad !

For image 2 and 3, the app still crashes though.

You can download them actually, when opening the image in a new tab, just rightglick anywhere except on the square in the middle, the "save as" button won't be greyed out here

**Comment by nevaran** [comment]
Gotcha

**Comment by nevaran** [comment]
Fixed it; I managed to find that it crashes somewhere in the **NewUri** method, which is being called on every new image it tries to load.
Not entirely sure which exactly is crashing it though, but it should handle the actual crash now
